name: Deploy Terraform for RDS

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  terraform_deploy:
    name: Deploy Terraform
    if: success('Validate Terraform Configuration')
    runs-on: ubuntu-latest
    needs: terraform_validate

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve \
        -var="db_username=${{ secrets.DB_USERNAME }}"
        -var="db_password=${{ secrets.DB_PASSWORD }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}